### ISSUE TITLE
ImportError: No module named pynotify

### ISSUE THREAD

**Issue by dotnetCarpenter** [abiczo/github-notifier#21]
### Reproduce
1. `sudo apt-get install python-setuptools python-gtk2 python-feedparser python-simplejson`
2. `git clone --depth=25 git://github.com/abiczo/github-notifier.git`
3. `cd github-notifier/ && python setup.py install`

### Error
```
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from githubnotifier import __version__
  File "/home/dotnet/projects/tools/github-notifier/githubnotifier.py", line 24, in <module>
    import pynotify
ImportError: No module named pynotify
```

### Environment
python --version Python 2.7.12
Ubuntu 16.04.1 LTS

**Comment by abiczo** [comment]
Thanks for reporting this! Could you try running

  sudo apt-get install python-notify 

and see if that helps?

**Comment by dotnetCarpenter** [comment]
It did. But I'm having permission issues. Perhaps `setup.py` should be run with elevated permission (root)?

For completeness:
**`python setup.py install`**
```
WARNING: '' not a valid package name; please use only .-separated package names in setup.py
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/test-easy-install-11807.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python2.7/dist-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://pythonhosted.org/setuptools/easy_install.html

Please make the appropriate changes for your system and try again.
```

**`sudo chown dotnet /usr/local/lib/python2.7/dist-packages/ && python setup.py install`**
```
WARNING: '' not a valid package name; please use only .-separated package names in setup.py
running install
running bdist_egg
running egg_info
creating github_notifier.egg-info
writing requirements to github_notifier.egg-info/requires.txt
writing github_notifier.egg-info/PKG-INFO
writing top-level names to github_notifier.egg-info/top_level.txt
writing dependency_links to github_notifier.egg-info/dependency_links.txt
writing entry points to github_notifier.egg-info/entry_points.txt
writing manifest file 'github_notifier.egg-info/SOURCES.txt'
reading manifest file 'github_notifier.egg-info/SOURCES.txt'
writing manifest file 'github_notifier.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-2.7
copying ./githubnotifier.py -> build/lib.linux-x86_64-2.7
copying ./octocat.png -> build/lib.linux-x86_64-2.7
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-2.7/githubnotifier.py -> build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-2.7/octocat.png -> build/bdist.linux-x86_64/egg
byte-compiling build/bdist.linux-x86_64/egg/githubnotifier.py to githubnotifier.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying github_notifier.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying github_notifier.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying github_notifier.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying github_notifier.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying github_notifier.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying github_notifier.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying github_notifier.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating dist
creating 'dist/github_notifier-0.1-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing github_notifier-0.1-py2.7.egg
creating /usr/local/lib/python2.7/dist-packages/github_notifier-0.1-py2.7.egg
Extracting github_notifier-0.1-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding github-notifier 0.1 to easy-install.pth file
Installing github-notifier script to /usr/local/bin
error: [Errno 13] Permission denied: '/usr/local/bin/github-notifier'
```

**Comment by dotnetCarpenter** [comment]
**`sudo python setup.py install`**
```
WARNING: '' not a valid package name; please use only .-separated package names in setup.py
running install
running bdist_egg
running egg_info
writing requirements to github_notifier.egg-info/requires.txt
writing github_notifier.egg-info/PKG-INFO
writing top-level names to github_notifier.egg-info/top_level.txt
writing dependency_links to github_notifier.egg-info/dependency_links.txt
writing entry points to github_notifier.egg-info/entry_points.txt
reading manifest file 'github_notifier.egg-info/SOURCES.txt'
writing manifest file 'github_notifier.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-2.7/githubnotifier.py -> build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-2.7/octocat.png -> build/bdist.linux-x86_64/egg
byte-compiling build/bdist.linux-x86_64/egg/githubnotifier.py to githubnotifier.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying github_notifier.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying github_notifier.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying github_notifier.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying github_notifier.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying github_notifier.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying github_notifier.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying github_notifier.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/github_notifier-0.1-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing github_notifier-0.1-py2.7.egg
removing '/usr/local/lib/python2.7/dist-packages/github_notifier-0.1-py2.7.egg' (and everything under it)
creating /usr/local/lib/python2.7/dist-packages/github_notifier-0.1-py2.7.egg
Extracting github_notifier-0.1-py2.7.egg to /usr/local/lib/python2.7/dist-packages
github-notifier 0.1 is already the active version in easy-install.pth
Installing github-notifier script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/github_notifier-0.1-py2.7.egg
Processing dependencies for github-notifier==0.1
Searching for feedparser==5.1.3
Best match: feedparser 5.1.3
Adding feedparser 5.1.3 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Finished processing dependencies for github-notifier==0.1
```

**Comment by abiczo** [comment]
Looks like `sudo python setup.py install` succeeded? If so, can you run github notifier now? Do you still see the `ImportError: No module named pynotify` error message after doing `sudo apt-get install python-notify`?

**Comment by dotnetCarpenter** [comment]
I actually could not see the icon in Ubuntu unity. I just switch to mate, yesterday and now I can see the icon. Just added some people to `/.githubnotifier/config.cfg` and awaiting notifications :)

**Comment by STech407** [comment]
I am having this same issue. I followed along in the comments except I'm getting "E: Package 'python-notify' has no installation candidate". Can someone please help I've researched and googled and can't find anything! I am stuck...

**Comment by abiczo** [comment]
@STech407 What OS are you using? Maybe someone with the same OS could help.

**Comment by STech407** [comment]
Kali Linux. I was trying to teach myself MITMf but am stuck there...

**Comment by Fbabsail** [comment]
> Kali Linux. I was trying to teach myself MITMf but am stuck there...

did you find the solution?
I have the same problem

**Comment by dotnetCarpenter** [comment]
wait, are you using github-notifier to practice Man In The Middle attacks?
Jeez!

**Comment by dotnetCarpenter** [comment]
Anyway [bettercap](https://github.com/bettercap/bettercap) seems like a better tool than MITMf.

**Comment by Fbabsail** [comment]
> Anyway [bettercap](https://github.com/bettercap/bettercap) seems like a better tool than MITMf.

I am trying to do the flip images attack and the replace images attack and I don't know how to do it on bettercap
